config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"
  ActiveAdmin.routes(self)
  devise_for :delivery_managers, ActiveAdmin::Devise.config

  devise_for :couriers, defaults: { format: :json },
             path: "/api/v1/",
             controllers: {
                 sessions: "api/v1/sessions"
             }


  namespace :api, defaults: { format: :json } do
      namespace :v1 do
          resources :couriers do
            resources :packages
          end
          get "/packages", to: "packages#all_packages"
          get "/packages/:id/confirm", to: "packages#generate_confirm_delivery_url"
          post "/packages/:id/confirm_delivery", to: "packages#confirm_delivery_url"
        end
    end



  root "admin/dashboard#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/courier.rb
# frozen_string_literal: true

class Courier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  mount_uploader :driver_licence, ImageUploader

  self.skip_session_storage = [:http_auth, :params_auth]

  def to_s
    email.to_s
  end

  has_many :package_assignment, dependent: :destroy
  has_many :packages, through: :package_assignment
end

app/controllers/api/v1/couriers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CouriersController < ApiController
      def index
        @couriers = Courier.all
        render json: @couriers
      end

      def show
        @courier = Courier.find(user_params)
        render json: @courier.as_json(only: [:id, :email])
      end

      def update
        @courier = Courier.find(params[:id])
        return render json: { msg: "Image already exist" }, status: :not_acceptable if @courier.driver_licence.present?

        @courier.update(driver_licence: params[:driver_licence])
        render json: { msg: "Driver licence was upload" }
      end

      private
        def user_params
          params.require(:courier).permit(:email, :password, :driver_licence)
        end
    end
  end
end

app/controllers/couriers_controller.rb
# frozen_string_literal: true

class CouriersController < ApplicationController
  def index
    @couriers = Courier.all.order(created_at: :desc)
  end

  def show
    @courier = Courier.find(params[:id])
    @package = Package.new
  end


  def new
    @courier = Courier.new
  end


  def edit
    @courier = Courier.find(params[:id])
  end


  def create
    @courier = Courier.new(courier_params)

    if @courier.save
      redirect_to @courier
    else
      render :new
    end
  end


  def update
    @courier = Courier.find(params[:id])

    if @courier.update(courier_params)
      redirect_to @courier
    else
      render :edit
    end
  end

  def destroy
    @courier = Courier.find(params[:id])
    @courier.destroy

    redirect_to couriers_path
  end

  private
    def courier_params
      params.require(:courier).permit(:name, :email)
    end
end

app/helpers/couriers_helper.rb
# frozen_string_literal: true

module CouriersHelper
end

app/views/couriers/edit.html.erb
<h1>Edit Courier</h1>
 
<%= form_with(model: @courier, local: true) do |form| %>
    
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back to list', couriers_path %>

app/views/couriers/index.html.erb
<h1>Control panel of Couriers</h1>


<form>
  <button><%= link_to 'New courier', new_courier_path %></button>
  <button><%= link_to 'ActiveAdmin', admin_root_path %></button>
</form>


<% if @couriers.size > 0 %>
  <table>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
<% end %>

<% @couriers.each do |couriers| %> <!--foreach for all couriers-->

  <tr>

    <td><%= couriers.name %></td>
    <td><%= couriers.email %></td>
    <td><%= link_to 'Show', courier_path(couriers) %></td>
    <td><%= link_to 'Edit', edit_courier_path(couriers) %></td>
    <td><%= link_to 'Delete', courier_path(couriers),
                    method: :delete,
                    data: {confirm: 'Are you sure?'} %></td>
  </tr>
<% end %>

</table>

app/views/couriers/new.html.erb
<h1> Add Courier</h1>

<%= form_with scope: :package, url: couriers_path, local: true do |form| %>




    <% if @courier.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@courier.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% @courier.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
  
<% end %>


 
<%= link_to 'Back to list', couriers_path %>

app/views/couriers/show.html.erb
<p><%= form_for [@courier, @package] do |f| %></p>
      <p>
        <%= f.label :track_number %><br>
        <%= f.text_field :tracking_number %>
      </p>

    <!--  Enable for show button status - In progress / Delivered
    <p>
      <%= f.label :status  %><br>
      <%= f.check_box :delivery_status %>
    </p>
    -->

    <p>
      <%= f.submit %>
    </p>
    <% end %>


<p>
  <strong>Name:</strong>
  <%= @courier.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @courier.email %>  
</p>

	<h3><%= link_to 'Edit', edit_courier_path(@courier) %> |
	<%= link_to 'Back to list', couriers_path %></h3>
  <ol>
  <% @courier.packages.each do |package| %> <!--foreach for all couriers-->


    <p>

      <li> <td><%= package.tracking_number %></td>
        <td><% if package.delivery_status %>
            Delivered
          <% else %>
            In progress
          <% end %></td>
      </li>
   </p>







  <% end %> </ol>